%% Stack Tensors
%
%  DESCRIPTION: This file takes in a table of tensors and stacks them
%  
%  PARAMETERS:
%   1. tensor_table: generated by 1 of the load functions. All load
%   functions produce similarly formated data tables, which is where
%   tensor_table is passed as a parameter from
%
%  RETURNS:
%   1. stacked_tensors: this is a cell array of tensors, where each tensor
%   is generated by stacking 1 column of tensors from tensor_table in a new
%   mode
%
% Joshua Pickard jpic@umich.edu

function stacked_tensors = stack_tensors(tensor_table)
    stacked_tensors = {};
    tensor_table_size = size(tensor_table);
    for column=1:tensor_table_size(2)
        column_of_tensors = tensor_table(:,column);
        tensor_size = [size(column_of_tensors{1}), tensor_table_size(1)];
        place_holder = {};
        for i=1:(length(tensor_size)-1)
            place_holder{end+1} = ':';
        end
        stack = tenzeros(tensor_size);
        for j = 1:tensor_table_size(1)
            stack(place_holder{:},j) = column_of_tensors{j};
        end
        stacked_tensors{end+1} = stack;
    end
end
