function [] = plot_hrv_tautstring(hrv, ts, epsilon, region_to_view)
%
% PLOT_TAUT_STRING will create a plot the HRV signal, its taut string
% estimate, including the upper and lower bounds
%
% INPUTS:
%   hrv             HRV signal (vector)
%   ts              Taut String estimate of HRV, generated by taut_string()
%   epsilon         Value of epsilon that was used in taut_string() to create ts
%   region_to_view  Optional: the tndices of the hrv and ts vectors that 
%                   you want to plot
%
% OUTPUTS:
%   None            There are no outputs but a figure is created and the
%                   data are plotted

ts_plotopt = 'bo-';
hrv_plotopt = 'k';
ub_plotopt = 'r';
lb_plotopt = 'g';

figure;

if nargin < 4
    plot(ts, ts_plotopt); hold on;
    plot(hrv,hrv_plotopt); 
    plot(hrv + epsilon,ub_plotopt); 
    plot(hrv - epsilon, lb_plotopt);
else
    plot(region_to_view, ts(region_to_view), ts_plotopt); hold on;
    plot(region_to_view, hrv(region_to_view), hrv_plotopt); 
    plot(region_to_view, hrv(region_to_view) + epsilon, ub_plotopt); 
    plot(region_to_view, hrv(region_to_view) - epsilon, lb_plotopt);
end

title(sprintf('Epsilon = %d', epsilon));
legend('Taut String', 'HRV', 'Upper Bound', 'Lower Bound');
hold off;

end %eof
